// Regenerate src/abi/*.ts from the Foundry artifacts in ../out (run `forge build` first).
import { readFileSync, writeFileSync, unlinkSync, existsSync } from "node:fs";
for (const c of ["RoyaltyRouterFactory", "RoyaltyRouter", "IMintClubBond", "IGlueHookMin"]) {
  const art = JSON.parse(readFileSync(new URL(`../../out/${c}.sol/${c}.json`, import.meta.url)));
  writeFileSync(new URL(`../src/abi/${c}.ts`, import.meta.url), `// generated by scripts/abi.mjs — do not edit\nexport default ${JSON.stringify(art.abi, null, 2)} as const;\n`);
  const j = new URL(`../src/abi/${c}.json`, import.meta.url);
  if (existsSync(j)) unlinkSync(j);
}
console.log("abis updated");
