// generated by scripts/abi.mjs — do not edit
export default [
  {
    "type": "function",
    "name": "NATIVEWRAP",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "address",
        "internalType": "address"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "addProgramLiquidity",
    "inputs": [
      {
        "name": "key",
        "type": "tuple",
        "internalType": "struct IGlueHookMin.PoolKey",
        "components": [
          {
            "name": "currency0",
            "type": "address",
            "internalType": "address"
          },
          {
            "name": "currency1",
            "type": "address",
            "internalType": "address"
          },
          {
            "name": "fee",
            "type": "uint24",
            "internalType": "uint24"
          },
          {
            "name": "tickSpacing",
            "type": "int24",
            "internalType": "int24"
          },
          {
            "name": "hooks",
            "type": "address",
            "internalType": "address"
          }
        ]
      },
      {
        "name": "liquidity",
        "type": "uint128",
        "internalType": "uint128"
      }
    ],
    "outputs": [
      {
        "name": "amount0",
        "type": "uint256",
        "internalType": "uint256"
      },
      {
        "name": "amount1",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "stateMutability": "payable"
  },
  {
    "type": "function",
    "name": "donate",
    "inputs": [
      {
        "name": "key",
        "type": "tuple",
        "internalType": "struct IGlueHookMin.PoolKey",
        "components": [
          {
            "name": "currency0",
            "type": "address",
            "internalType": "address"
          },
          {
            "name": "currency1",
            "type": "address",
            "internalType": "address"
          },
          {
            "name": "fee",
            "type": "uint24",
            "internalType": "uint24"
          },
          {
            "name": "tickSpacing",
            "type": "int24",
            "internalType": "int24"
          },
          {
            "name": "hooks",
            "type": "address",
            "internalType": "address"
          }
        ]
      },
      {
        "name": "amount",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "outputs": [
      {
        "name": "credited",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "stateMutability": "payable"
  },
  {
    "type": "function",
    "name": "harvest",
    "inputs": [
      {
        "name": "key",
        "type": "tuple",
        "internalType": "struct IGlueHookMin.PoolKey",
        "components": [
          {
            "name": "currency0",
            "type": "address",
            "internalType": "address"
          },
          {
            "name": "currency1",
            "type": "address",
            "internalType": "address"
          },
          {
            "name": "fee",
            "type": "uint24",
            "internalType": "uint24"
          },
          {
            "name": "tickSpacing",
            "type": "int24",
            "internalType": "int24"
          },
          {
            "name": "hooks",
            "type": "address",
            "internalType": "address"
          }
        ]
      }
    ],
    "outputs": [
      {
        "name": "mainFees",
        "type": "uint256",
        "internalType": "uint256"
      },
      {
        "name": "secondaryFees",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "launchPool",
    "inputs": [
      {
        "name": "key",
        "type": "tuple",
        "internalType": "struct IGlueHookMin.PoolKey",
        "components": [
          {
            "name": "currency0",
            "type": "address",
            "internalType": "address"
          },
          {
            "name": "currency1",
            "type": "address",
            "internalType": "address"
          },
          {
            "name": "fee",
            "type": "uint24",
            "internalType": "uint24"
          },
          {
            "name": "tickSpacing",
            "type": "int24",
            "internalType": "int24"
          },
          {
            "name": "hooks",
            "type": "address",
            "internalType": "address"
          }
        ]
      },
      {
        "name": "sqrtPriceX96",
        "type": "uint160",
        "internalType": "uint160"
      },
      {
        "name": "main",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "recipient",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "tickLower",
        "type": "int24",
        "internalType": "int24"
      },
      {
        "name": "tickUpper",
        "type": "int24",
        "internalType": "int24"
      },
      {
        "name": "liquidity",
        "type": "uint128",
        "internalType": "uint128"
      },
      {
        "name": "owner",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "config",
        "type": "tuple",
        "internalType": "struct IGlueHookMin.ProgramConfig",
        "components": [
          {
            "name": "buybackShareWad",
            "type": "uint64",
            "internalType": "uint64"
          },
          {
            "name": "burnShareWad",
            "type": "uint64",
            "internalType": "uint64"
          },
          {
            "name": "compoundShareWad",
            "type": "uint64",
            "internalType": "uint64"
          },
          {
            "name": "potCompoundShareWad",
            "type": "uint64",
            "internalType": "uint64"
          },
          {
            "name": "potBurnShareWad",
            "type": "uint64",
            "internalType": "uint64"
          },
          {
            "name": "publicHarvest",
            "type": "bool",
            "internalType": "bool"
          },
          {
            "name": "secondaryRecipient",
            "type": "address",
            "internalType": "address"
          },
          {
            "name": "mainRecipient",
            "type": "address",
            "internalType": "address"
          },
          {
            "name": "minMain",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "minSecondary",
            "type": "uint256",
            "internalType": "uint256"
          }
        ]
      }
    ],
    "outputs": [
      {
        "name": "amount0",
        "type": "uint256",
        "internalType": "uint256"
      },
      {
        "name": "amount1",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "stateMutability": "payable"
  },
  {
    "type": "function",
    "name": "potOf",
    "inputs": [
      {
        "name": "poolId",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ],
    "outputs": [
      {
        "name": "pot",
        "type": "tuple",
        "internalType": "struct IGlueHookMin.Pot",
        "components": [
          {
            "name": "admin",
            "type": "address",
            "internalType": "address"
          },
          {
            "name": "main",
            "type": "address",
            "internalType": "address"
          },
          {
            "name": "secondary",
            "type": "address",
            "internalType": "address"
          },
          {
            "name": "recipient",
            "type": "address",
            "internalType": "address"
          },
          {
            "name": "configured",
            "type": "bool",
            "internalType": "bool"
          },
          {
            "name": "balance",
            "type": "uint256",
            "internalType": "uint256"
          }
        ]
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "programOf",
    "inputs": [
      {
        "name": "poolId",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ],
    "outputs": [
      {
        "name": "program",
        "type": "tuple",
        "internalType": "struct IGlueHookMin.Program",
        "components": [
          {
            "name": "liquidity",
            "type": "uint128",
            "internalType": "uint128"
          },
          {
            "name": "tickLower",
            "type": "int24",
            "internalType": "int24"
          },
          {
            "name": "tickUpper",
            "type": "int24",
            "internalType": "int24"
          },
          {
            "name": "exists",
            "type": "bool",
            "internalType": "bool"
          },
          {
            "name": "publicHarvest",
            "type": "bool",
            "internalType": "bool"
          },
          {
            "name": "buybackShareWad",
            "type": "uint64",
            "internalType": "uint64"
          },
          {
            "name": "owner",
            "type": "address",
            "internalType": "address"
          },
          {
            "name": "burnShareWad",
            "type": "uint64",
            "internalType": "uint64"
          },
          {
            "name": "secondaryRecipient",
            "type": "address",
            "internalType": "address"
          },
          {
            "name": "compoundShareWad",
            "type": "uint64",
            "internalType": "uint64"
          },
          {
            "name": "mainRecipient",
            "type": "address",
            "internalType": "address"
          },
          {
            "name": "potCompoundShareWad",
            "type": "uint64",
            "internalType": "uint64"
          },
          {
            "name": "operator",
            "type": "address",
            "internalType": "address"
          },
          {
            "name": "potBurnShareWad",
            "type": "uint64",
            "internalType": "uint64"
          },
          {
            "name": "minMain",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "minSecondary",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "carryMain",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "carrySecondary",
            "type": "uint256",
            "internalType": "uint256"
          }
        ]
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "removeProgramLiquidity",
    "inputs": [
      {
        "name": "key",
        "type": "tuple",
        "internalType": "struct IGlueHookMin.PoolKey",
        "components": [
          {
            "name": "currency0",
            "type": "address",
            "internalType": "address"
          },
          {
            "name": "currency1",
            "type": "address",
            "internalType": "address"
          },
          {
            "name": "fee",
            "type": "uint24",
            "internalType": "uint24"
          },
          {
            "name": "tickSpacing",
            "type": "int24",
            "internalType": "int24"
          },
          {
            "name": "hooks",
            "type": "address",
            "internalType": "address"
          }
        ]
      },
      {
        "name": "liquidity",
        "type": "uint128",
        "internalType": "uint128"
      },
      {
        "name": "to",
        "type": "address",
        "internalType": "address"
      }
    ],
    "outputs": [
      {
        "name": "amount0",
        "type": "uint256",
        "internalType": "uint256"
      },
      {
        "name": "amount1",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "setProgramConfig",
    "inputs": [
      {
        "name": "poolId",
        "type": "bytes32",
        "internalType": "bytes32"
      },
      {
        "name": "config",
        "type": "tuple",
        "internalType": "struct IGlueHookMin.ProgramConfig",
        "components": [
          {
            "name": "buybackShareWad",
            "type": "uint64",
            "internalType": "uint64"
          },
          {
            "name": "burnShareWad",
            "type": "uint64",
            "internalType": "uint64"
          },
          {
            "name": "compoundShareWad",
            "type": "uint64",
            "internalType": "uint64"
          },
          {
            "name": "potCompoundShareWad",
            "type": "uint64",
            "internalType": "uint64"
          },
          {
            "name": "potBurnShareWad",
            "type": "uint64",
            "internalType": "uint64"
          },
          {
            "name": "publicHarvest",
            "type": "bool",
            "internalType": "bool"
          },
          {
            "name": "secondaryRecipient",
            "type": "address",
            "internalType": "address"
          },
          {
            "name": "mainRecipient",
            "type": "address",
            "internalType": "address"
          },
          {
            "name": "minMain",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "minSecondary",
            "type": "uint256",
            "internalType": "uint256"
          }
        ]
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "setProgramOperator",
    "inputs": [
      {
        "name": "poolId",
        "type": "bytes32",
        "internalType": "bytes32"
      },
      {
        "name": "newOperator",
        "type": "address",
        "internalType": "address"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "transferProgramOwnership",
    "inputs": [
      {
        "name": "poolId",
        "type": "bytes32",
        "internalType": "bytes32"
      },
      {
        "name": "newOwner",
        "type": "address",
        "internalType": "address"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  }
] as const;
