// generated by scripts/abi.mjs — do not edit
export default [
  {
    "type": "function",
    "name": "claimRoyalties",
    "inputs": [
      {
        "name": "reserveToken",
        "type": "address",
        "internalType": "address"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "createToken",
    "inputs": [
      {
        "name": "tp",
        "type": "tuple",
        "internalType": "struct IMintClubBond.TokenParams",
        "components": [
          {
            "name": "name",
            "type": "string",
            "internalType": "string"
          },
          {
            "name": "symbol",
            "type": "string",
            "internalType": "string"
          }
        ]
      },
      {
        "name": "bp",
        "type": "tuple",
        "internalType": "struct IMintClubBond.BondParams",
        "components": [
          {
            "name": "mintRoyalty",
            "type": "uint16",
            "internalType": "uint16"
          },
          {
            "name": "burnRoyalty",
            "type": "uint16",
            "internalType": "uint16"
          },
          {
            "name": "reserveToken",
            "type": "address",
            "internalType": "address"
          },
          {
            "name": "maxSupply",
            "type": "uint128",
            "internalType": "uint128"
          },
          {
            "name": "stepRanges",
            "type": "uint128[]",
            "internalType": "uint128[]"
          },
          {
            "name": "stepPrices",
            "type": "uint128[]",
            "internalType": "uint128[]"
          }
        ]
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "address",
        "internalType": "address"
      }
    ],
    "stateMutability": "payable"
  },
  {
    "type": "function",
    "name": "creationFee",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "getReserveForToken",
    "inputs": [
      {
        "name": "token",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "tokensToMint",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "outputs": [
      {
        "name": "reserveAmount",
        "type": "uint256",
        "internalType": "uint256"
      },
      {
        "name": "royalty",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "mint",
    "inputs": [
      {
        "name": "token",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "tokensToMint",
        "type": "uint256",
        "internalType": "uint256"
      },
      {
        "name": "maxReserveAmount",
        "type": "uint256",
        "internalType": "uint256"
      },
      {
        "name": "receiver",
        "type": "address",
        "internalType": "address"
      }
    ],
    "outputs": [
      {
        "name": "reserveAmount",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "priceForNextMint",
    "inputs": [
      {
        "name": "token",
        "type": "address",
        "internalType": "address"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "uint128",
        "internalType": "uint128"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "tokenBond",
    "inputs": [
      {
        "name": "token",
        "type": "address",
        "internalType": "address"
      }
    ],
    "outputs": [
      {
        "name": "creator",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "mintRoyalty",
        "type": "uint16",
        "internalType": "uint16"
      },
      {
        "name": "burnRoyalty",
        "type": "uint16",
        "internalType": "uint16"
      },
      {
        "name": "createdAt",
        "type": "uint40",
        "internalType": "uint40"
      },
      {
        "name": "reserveToken",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "reserveBalance",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "updateBondCreator",
    "inputs": [
      {
        "name": "token",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "creator",
        "type": "address",
        "internalType": "address"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "userTokenRoyaltyBalance",
    "inputs": [
      {
        "name": "user",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "reserveToken",
        "type": "address",
        "internalType": "address"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "stateMutability": "view"
  }
] as const;
