// generated by scripts/abi.mjs — do not edit
export default [
  {
    "type": "constructor",
    "inputs": [
      {
        "name": "bond",
        "type": "address",
        "internalType": "contract IMintClubBond"
      },
      {
        "name": "hook",
        "type": "address",
        "internalType": "contract IGlueHookMin"
      },
      {
        "name": "poolManager",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "governance_",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "dao_",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "daoBps_",
        "type": "uint16",
        "internalType": "uint16"
      },
      {
        "name": "maxDaoBps",
        "type": "uint16",
        "internalType": "uint16"
      },
      {
        "name": "stalePeriod",
        "type": "uint64",
        "internalType": "uint64"
      },
      {
        "name": "gracePeriod",
        "type": "uint64",
        "internalType": "uint64"
      }
    ],
    "stateMutability": "nonpayable"
  },
  {
    "type": "receive",
    "stateMutability": "payable"
  },
  {
    "type": "function",
    "name": "BOND",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "address",
        "internalType": "contract IMintClubBond"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "GRACE_PERIOD",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "uint64",
        "internalType": "uint64"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "HOOK",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "address",
        "internalType": "contract IGlueHookMin"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "MAX_DAO_BPS",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "uint16",
        "internalType": "uint16"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "POOL_MANAGER",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "address",
        "internalType": "address"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "STALE_PERIOD",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "uint64",
        "internalType": "uint64"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "dao",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "address",
        "internalType": "address"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "daoBps",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "uint16",
        "internalType": "uint16"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "feeInfo",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "",
        "type": "uint16",
        "internalType": "uint16"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "governance",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "address",
        "internalType": "address"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "launch",
    "inputs": [
      {
        "name": "L",
        "type": "tuple",
        "internalType": "struct RoyaltyRouterFactory.Launch",
        "components": [
          {
            "name": "name",
            "type": "string",
            "internalType": "string"
          },
          {
            "name": "symbol",
            "type": "string",
            "internalType": "string"
          },
          {
            "name": "bond",
            "type": "tuple",
            "internalType": "struct IMintClubBond.BondParams",
            "components": [
              {
                "name": "mintRoyalty",
                "type": "uint16",
                "internalType": "uint16"
              },
              {
                "name": "burnRoyalty",
                "type": "uint16",
                "internalType": "uint16"
              },
              {
                "name": "reserveToken",
                "type": "address",
                "internalType": "address"
              },
              {
                "name": "maxSupply",
                "type": "uint128",
                "internalType": "uint128"
              },
              {
                "name": "stepRanges",
                "type": "uint128[]",
                "internalType": "uint128[]"
              },
              {
                "name": "stepPrices",
                "type": "uint128[]",
                "internalType": "uint128[]"
              }
            ]
          },
          {
            "name": "curveMint",
            "type": "uint128",
            "internalType": "uint128"
          },
          {
            "name": "maxReserveIn",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "secondary",
            "type": "address",
            "internalType": "address"
          },
          {
            "name": "fee",
            "type": "uint24",
            "internalType": "uint24"
          },
          {
            "name": "tickSpacing",
            "type": "int24",
            "internalType": "int24"
          },
          {
            "name": "sqrtPriceX96",
            "type": "uint160",
            "internalType": "uint160"
          },
          {
            "name": "liquidity",
            "type": "uint128",
            "internalType": "uint128"
          },
          {
            "name": "secondarySeed",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "compoundShareWad",
            "type": "uint64",
            "internalType": "uint64"
          },
          {
            "name": "feeRecipient",
            "type": "address",
            "internalType": "address"
          },
          {
            "name": "minMain",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "minSecondary",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "swapper",
            "type": "address",
            "internalType": "address"
          },
          {
            "name": "bountyBps",
            "type": "uint16",
            "internalType": "uint16"
          },
          {
            "name": "minClaim",
            "type": "uint256",
            "internalType": "uint256"
          }
        ]
      }
    ],
    "outputs": [
      {
        "name": "token",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "router",
        "type": "address",
        "internalType": "address"
      }
    ],
    "stateMutability": "payable"
  },
  {
    "type": "function",
    "name": "predict",
    "inputs": [
      {
        "name": "token",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "key",
        "type": "tuple",
        "internalType": "struct IGlueHookMin.PoolKey",
        "components": [
          {
            "name": "currency0",
            "type": "address",
            "internalType": "address"
          },
          {
            "name": "currency1",
            "type": "address",
            "internalType": "address"
          },
          {
            "name": "fee",
            "type": "uint24",
            "internalType": "uint24"
          },
          {
            "name": "tickSpacing",
            "type": "int24",
            "internalType": "int24"
          },
          {
            "name": "hooks",
            "type": "address",
            "internalType": "address"
          }
        ]
      },
      {
        "name": "swapper",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "bountyBps",
        "type": "uint16",
        "internalType": "uint16"
      },
      {
        "name": "minClaim",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "address",
        "internalType": "address"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "setFee",
    "inputs": [
      {
        "name": "dao_",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "daoBps_",
        "type": "uint16",
        "internalType": "uint16"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "setGovernance",
    "inputs": [
      {
        "name": "governance_",
        "type": "address",
        "internalType": "address"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "event",
    "name": "FeeSet",
    "inputs": [
      {
        "name": "dao",
        "type": "address",
        "indexed": true,
        "internalType": "address"
      },
      {
        "name": "daoBps",
        "type": "uint16",
        "indexed": false,
        "internalType": "uint16"
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "GovernanceSet",
    "inputs": [
      {
        "name": "governance",
        "type": "address",
        "indexed": true,
        "internalType": "address"
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "Launched",
    "inputs": [
      {
        "name": "token",
        "type": "address",
        "indexed": true,
        "internalType": "address"
      },
      {
        "name": "poolId",
        "type": "bytes32",
        "indexed": true,
        "internalType": "bytes32"
      },
      {
        "name": "router",
        "type": "address",
        "indexed": false,
        "internalType": "address"
      }
    ],
    "anonymous": false
  },
  {
    "type": "error",
    "name": "BadDao",
    "inputs": []
  },
  {
    "type": "error",
    "name": "BadPeriods",
    "inputs": []
  },
  {
    "type": "error",
    "name": "BadRoute",
    "inputs": []
  },
  {
    "type": "error",
    "name": "NotGovernance",
    "inputs": []
  },
  {
    "type": "error",
    "name": "PredictionMismatch",
    "inputs": []
  },
  {
    "type": "error",
    "name": "RefundFailed",
    "inputs": []
  }
] as const;
